Changed from using username as volume name to using part of the path as the volume name Fixed diagnostic information to go to stderr

diff --git a/dockervolume b/dockervolume
--- a/dockervolume
+++ b/dockervolume
@@ -3,37 +3,39 @@
 # Create an image called "rsync" on your docker host that includes the rsync
 # command, then you can rsync to and from any volume on that host like so:
 #
-#   rsync -a --rsh=./dockervolume volumename@dockerhost:/mnt/ local/folder
+#   rsync -a --rsh=./dockervolume user@dockerhost:/mnt/volumename/ local/folder
 #
 # This command will mount volumename at /mnt in a temporary container on
 # dockerhost and copy everything to the local folder local/folder
 #
 # The remote path must start with "/mnt/" because that is where the docker
-# volume is mounted inside the temporary container.  Other than that, though,
-# you should be able to do all the usual rsync things.
+# volume is mounted inside the temporary container, and include at least
+# one other path component to serve as the volume name.  Other than that,
+# though, you should be able to do all the usual rsync things.
 #
 # Watch out for spaces in pathnames and such!  This script could break easily
 # and has had virtually no testing done to it.
 
-# check that there is a user (volume) specified
-if [ "$1" != "-l" ] ; then
-	echo "Need volume name (specify as username)"
-	exit 2
-fi
-
-# check that the path starts with /mnt
+# check that the path starts with /mnt/ and contains a volume name
 PATHARG=${!#}
-if [ "$PATHARG" == "${PATHARG#/mnt/}" ] ; then
-	echo "Path must start with '/mnt'"
+PATHCHK=${PATHARG#/mnt/}
+VOLUME=${PATHCHK%%/*}
+if [ "$PATHARG" == "$PATHCHK" -o "$VOLUME" == "$PATHCHK" ] ; then
+	echo "${0##*/} shell helper: remote path '$PATHARG' invalid; format is /mnt/VOLUMENAME/[...]" >&2
 	exit 2
 fi
 
-# grab args
-shift
-VOLUME="$1"
-shift
+# check for login (username)
+if [ "$1" == "-l" ] ; then
+	shift
+	LOGINARG="-l $1"
+	shift
+fi
 
+# capture hostname
 HOST="$1"
+
+# remaining args are rsync invocation
 shift
 
-ssh $HOST docker run -i --rm --volume=$VOLUME:/mnt rsync $@
+ssh $LOGINARG $HOST docker run -i --rm --volume=$VOLUME:/mnt/$VOLUME rsync $@
